// This file is auto generated by the build script. Do not edit manually.
#ifndef CLE_MATMUL_H
#define CLE_MATMUL_H

#include "array.hpp"
#include "backend.hpp"
#include "execution.hpp"

namespace kernel {

	constexpr const char* matmul = R"(
        extern "C" __global__ void matmul(/* const Array & dA, const Array & dB, const Array & dC, */ int n) {
            int i = threadIdx.x + blockIdx.x * blockDim.x;
            int j = threadIdx.y + blockIdx.y * blockDim.y; 
            size_t size = 4 * 4 * 1;

            // printf("hello ");

            if (i < n && j < n)
            {
                // float data_out[size];
                // dA.read(data_out);
                // for (int i = 0; i < size; i++)
                // {
                //     std::cout << data_out[i] << " ";
                // }
                // std::cout << std::endl;
                // float c = 0;
                // for (int k = 0; k < n; k++)
                // {
                //     printf("%f ", dA[i * n + k]);
                //     // c += dA[i * n + k] * dB[k + j * n];
                // }
                // dC[i * n + j] = c;
            }
        }
    )";

}

 // end of namespace kernel
#endif // CLE_MATMUL_H
