
name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:

    build: 

        runs-on: ${{ matrix.os }}
        name: build-${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]

        steps:

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install dependencies
              run: |
                if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
                  sudo apt-get update   
                  sudo apt-get install -y nvidia-cuda-toolkit 
                  sudo ldconfig /usr/local/cuda/lib64
                elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
                  brew update
                  brew install opencl
                  brew install --cask cuda
                else
                  choco install opencl-sdk
                  choco install cuda
                fi
      
            - name: Setup cmake
              uses: lukka/get-cmake@v3.26.3

            - name: Configure and build project
              run: |
                cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CUDA_ARCHITECTURES=61
                cmake --build build --config Release -j 4 

            
