
name: Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:

    build: 

        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                cuda_version: [11.2]

        steps:

            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up OpenCL
              run: |
                sudo apt update
                sudo apt install -y ocl-icd-opencl-dev
    
            - name: Set up CUDA Toolkit
              uses: nvidia/setup-cuda@v{{ matrix.cuda_version }}
              with:
                cuda: '{{ matrix.cuda_version }}'
        
            - name: Setup cmake
              uses: lukka/get-cmake@v3.26.3

            
