
name: Build

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:

    build: 

        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                cuda_version: [11.2]

        steps:

            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up OpenCL
              run: |
                sudo apt update
                sudo apt install -y ocl-icd-opencl-dev
    
            - name: Install CUDA Toolkit
              run: |
                wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
                sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
                wget https://developer.download.nvidia.com/compute/cuda/11.4.1/local_installers/cuda-repo-ubuntu2004-11-4-local_11.4.1-470.57.02-1_amd64.deb
                sudo dpkg -i cuda-repo-ubuntu2004-11-4-local_11.4.1-470.57.02-1_amd64.deb
                sudo apt-key add /var/cuda-repo-ubuntu2004-11-4-local/7fa2af80.pub
                sudo apt-get update
                sudo apt-get -y install cuda
      
            - name: Setup cmake
              uses: lukka/get-cmake@v3.26.3

            
